Vios Maintenance module PR
ansible-hmc-org/ansible-power-hmc pull request #52
Opened 2024-08-23 07:57 UTC by SreenidhiS1

2024-08-23 08:42 UTC, naveenkandakur requested changes

2024-08-23 08:42 UTC, naveenkandakur commented on plugins/modules/vios_maintenance.py
> +    - Anil Vijayan(@AnilVijayan)
you can change the author name to yours :)

2024-08-23 08:42 UTC, naveenkandakur commented on plugins/modules/vios_maintenance.py
> +                    - The name of the managed system which has the VIOS to back up.
typo, it should be backup not back up

2024-08-23 08:42 UTC, naveenkandakur commented on plugins/modules/vios_maintenance.py
> +            - The desired build state of the target HMC.
What is this line ?

2024-08-27 14:20 UTC, SreenidhiS1 commented
Created new PR so closing this

2024-08-27 14:20 UTC, closed without merging