added roles folder
ansible-hmc-org/ansible-power-hmc pull request #67
Opened 2024-11-14 21:09 UTC by manyaa14

2024-11-25 06:04 UTC, AnilVijayan requested changes

2024-11-25 06:04 UTC, AnilVijayan commented on plugins/modules/hmc_command.py
Ignore this file change

2024-11-25 06:04 UTC, AnilVijayan commented on playbooks/roles_passpolicy_playbook.yml
> +    - ../roles/password_policy/vars/secrets.yml
Do we need to explicitly specify var file since we have already kept this file in the roles file hierarchy where varfile is expected

2024-11-25 06:04 UTC, AnilVijayan commented on roles/password_policy/README.md
> +This role is named as Password Policy management for power HMC. It assists in checking if a password policy exists in a power HMC and modify it with new configurations or else creating a new password
The scope of this role encompasses managing typical password policy requirements for the client's Hardware Management Console (HMC). Key responsibilities include:
- Applying new policy requirements to existing policies
- Enforcing new policies across multiple HMCs
- Updating credentials for all locally authenticated HMC users to comply with new policy

2024-11-25 06:04 UTC, AnilVijayan commented on roles/password_policy/README.md
> +- password_policy_hmc_username:
`hmc_username` itself is enough right?

2024-11-25 06:04 UTC, AnilVijayan commented on roles/password_policy/README.md
> +    required: true
This should be optional i guess. If at all user wanted to change the password of all users, otherwise they can chose not to

2024-11-25 06:04 UTC, AnilVijayan commented on roles/password_policy/README.md
> +    description: specifies the existing and new password details for the users in the HMC. It can be stored in secrets.yml file in vars folder and can be encrypted using ansible-vault.
Instead of "It can be stored in secrets.yml file in vars folder and can be encrypted using ansible-vault."
For security purposes, it is highly recommended to store this sensitive information in an encrypted vault file

2024-11-25 06:04 UTC, AnilVijayan commented on roles/password_policy/README.md
> +- password_policy_hmc_password:
Move this to above along with `password_policy_hmc_username `
Also better provide name as  `hmc_username `

2024-11-25 06:04 UTC, AnilVijayan commented on roles/password_policy/handlers/main.yml
> +- name: Deactivate pass policies
Deactivate the password policy if any already existed and it is in activated state

2024-11-25 06:04 UTC, AnilVijayan commented on roles/password_policy/meta/main.yml
> +  # platforms:
Remove commented lines

2024-12-09 05:19 UTC, naveenkandakur requested changes

2024-12-09 05:19 UTC, naveenkandakur commented on playbooks/roles_passpolicy_playbook.yml
> +    # - role: password_policy
Remove the commented lines

2024-12-09 05:19 UTC, naveenkandakur commented on roles/password_policy/README.md
> +  gather_facts: false
Please provide working example playbook as below
# Main playbook for HMC Password policy Management
 - name: HMC Password Policy Management
   hosts: hmcs
   connection: local
   collections:
     - ibm.power_hmc
   gather_facts: false
   vars_files:
     - "{{ role_path }}/vars/secrets.yml"
   roles:
     - password_policy

2024-12-09 05:19 UTC, naveenkandakur commented on roles/password_policy/tasks/main.yml
> +- name: Create a new password policy in power HMC if the policy name doesn't already exists
Correct the name as below
Create a new password policy in power HMC if the policy name doesn't exists.

2024-12-09 05:19 UTC, naveenkandakur commented on roles/password_policy/vars/main.yml
> +password_policy_name: testnewagain2
Please provide some appropriate name like hmcpasswordpolicy1

2024-12-09 05:19 UTC, naveenkandakur commented on roles/password_policy/vars/secrets.yml
> +    passwd: "Abcde@12345"
I suggest don't hard code the password, you can let the user to define them just mention as <TODO_password> something like this

2024-12-09 05:19 UTC, naveenkandakur commented on roles/password_policy/vars/secrets.yml
> +password_policy_hmc_password: Abcde@1234
Same as above

2024-12-10 05:46 UTC, naveenkandakur approved these changes

2024-12-10 05:46 UTC, naveenkandakur commented on playbooks/roles_passpolicy_playbook.yml
> +- name: HMC Password Policy Management
Create/update/apply password policy and change the credential of the local HMC users accordingly

2024-12-10 05:47 UTC, merged